apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: testmesh-dev

resources:
  - ../../base

commonLabels:
  environment: dev

replicas:
  - name: testmesh-api
    count: 1
  - name: testmesh-web
    count: 1

configMapGenerator:
  - name: testmesh-config
    behavior: merge
    literals:
      - LOG_LEVEL=debug

patchesStrategicMerge:
  - resources-patch.yaml

images:
  - name: testmesh/api
    newTag: dev
  - name: testmesh/web
    newTag: dev
